"""caching avatar hashes

Revision ID: 2538539a4cd0
Revises: 23f917260c1
Create Date: 2015-07-26 22:19:28.280019

"""

# revision identifiers, used by Alembic.
revision = '2538539a4cd0'
down_revision = '23f917260c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
