"""user-confirmation

Revision ID: 2a4f9f833241
Revises: a380da0af1f
Create Date: 2015-07-20 16:23:46.499717

"""

# revision identifiers, used by Alembic.
revision = '2a4f9f833241'
down_revision = 'a380da0af1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
