"""initial migration

Revision ID: 490759ee758a
Revises: None
Create Date: 2015-07-16 14:29:53.314600

"""

# revision identifiers, used by Alembic.
revision = '490759ee758a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
