"""rich text posts

Revision ID: 4b9fc383e643
Revises: 6349566ed91
Create Date: 2015-08-02 15:43:44.552239

"""

# revision identifiers, used by Alembic.
revision = '4b9fc383e643'
down_revision = '6349566ed91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
